name: Auto TikTok Download

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: Download only new videos
        run: |
          mkdir -p videos
          yt-dlp \
            --download-archive archive.txt \
            -o "videos/%(title)s.%(ext)s" \
            https://www.tiktok.com/@teacher_linhlinh

      - name: Commit and push
        run: |
          git config --global user.name "auto-bot"
          git config --global user.email "auto@bot.com"
          git add .
          git commit -m "auto new video" || echo "no changes"
          git push
