name: Auto TikTok Download

on:
  schedule:
    - cron: '*/30 * * * *'  # chạy mỗi 30 phút
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: Download video
        run: |
          yt-dlp https://www.tiktok.com/@teacher_linhlinh
